{
  "openapi": "3.0.0",
  "info": {
    "title": "Buku Sawit Transaction Service",
    "description": "Service ini dipakai untuk melakukan pencacatan transaksi untuk sistem buku sawit.",
    "contact": {
      "email": "it@ninosoftwarehouse.id"
    },
    "version": "0.1.0"
  },
  "paths": {
    "/api/v1/sales": {
      "get": {
        "tags": [
          "Sales Transaction"
        ],
        "operationId": "getSales",
        "summary": "Get Recently Recorded Sales Transaction",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APISuccessResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "allOf": [
                              {
                                "type": "object",
                                "properties": {
                                  "id": {
                                    "type": "string"
                                  }
                                }
                              },
                              {
                                "$ref": "#/components/schemas/TransactionListResponse"
                              }
                            ]
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "message": "Sales Fetched Successfully",
                  "data": [
                    {
                      "id": "92cb1d94-85ee-4704-a4bf-43340807d717",
                      "productName": "TBS Plasma",
                      "transactionDate": "2023-07-24 15:00:25.120",
                      "totalWeight": 1500,
                      "receivedWeight": 750,
                      "total": 260000,
                      "paymentMethod": "Cash",
                      "paymentStatus": "Paid",
                      "deliveryStatus": "Partial Deliveed",
                      "isPaid": true,
                      "isDelivered": false
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/sale/{transactionId}": {
      "get": {
        "tags": [
          "Sales Transaction"
        ],
        "operationId": "getSalesTransactionById",
        "summary": "Get Sales Transaction By Id",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "transactionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APISuccessResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "object",
                          "allOf": [
                            {
                              "type": "object",
                              "properties": {
                                "id": {
                                  "type": "string"
                                }
                              }
                            },
                            {
                              "$ref": "#/components/schemas/TransactionDetailResponse"
                            }
                          ]
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "message": "Sales Detail Fetched Successfully",
                  "data": {
                    "id": "92cb1d94-85ee-4704-a4bf-43340807d717",
                    "productId": "92cb1d94-85ee-4704-a4bf-43340807d717",
                    "transactionDate": "2023-07-24 15:00:25.120",
                    "grossWeight": 2500,
                    "tareWeight": 1000,
                    "nettoWeight": 1500,
                    "dedicationPersentage": 4,
                    "totalWeight": 1440,
                    "receivedWeight": 750,
                    "price": 50000,
                    "total": 72000000,
                    "vehicleRegistrationNumber": "BK 123 ABC",
                    "paymentMethod": "Cash",
                    "paymentStatus": "Paid",
                    "deliveryStatus": "Partial Deliveed",
                    "sourceOfPurcahse": "-",
                    "additionalNotes": null,
                    "proofImages": [
                      "https://link.id/a",
                      "https://link.id/b",
                      "https://link.id/c"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/sale/store": {
      "post": {
        "tags": [
          "Sales Transaction"
        ],
        "operationId": "storeSales",
        "summary": "Store Sales Transaction",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionStoreBody"
              },
              "example": {
                "productId": "92cb1d94-85ee-4704-a4bf-43340807d717",
                "grossWeight": 2500,
                "tareWeight": 1000,
                "dedicationPersentage": 4,
                "receivedWeight": 750,
                "price": 50000,
                "total": 72000000,
                "vehicleRegistrationNumber": "BK 123 ABC",
                "paymentMethod": "Cash",
                "paymentStatus": "Paid",
                "deliveryStatus": "Partial Deliveed",
                "sourceOfPurcahse": "-",
                "additionalNotes": null,
                "proofImages": [
                  "blob string"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APISuccessResponse"
                },
                "example": {
                  "success": true,
                  "message": "Sales Data Stored Successfully"
                }
              }
            }
          },
          "400": {
            "description": "Sales Store Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APIErrorResponse"
                    },
                    {
                      "$ref": "#/components/schemas/APIValidationError"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/sale/update": {
      "put": {
        "tags": [
          "Sales Transaction"
        ],
        "operationId": "updateSales",
        "summary": "Update Sales Transaction",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      }
                    }
                  },
                  {
                    "$ref": "#/components/schemas/TransactionStoreBody"
                  }
                ]
              },
              "example": {
                "id": "92cb1d94-85ee-4704-a4bf-43340807d717",
                "productId": "92cb1d94-85ee-4704-a4bf-43340807d717",
                "grossWeight": 2500,
                "tareWeight": 1000,
                "dedicationPersentage": 4,
                "receivedWeight": 750,
                "price": 50000,
                "total": 72000000,
                "vehicleRegistrationNumber": "BK 123 ABC",
                "paymentMethod": "Cash",
                "paymentStatus": "Paid",
                "deliveryStatus": "Partial Deliveed",
                "sourceOfPurcahse": "-",
                "additionalNotes": null,
                "proofImages": [
                  "blob string"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APISuccessResponse"
                },
                "example": {
                  "success": true,
                  "message": "Sales Data Stored Successfully"
                }
              }
            }
          },
          "400": {
            "description": "Sales Store Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APIErrorResponse"
                    },
                    {
                      "$ref": "#/components/schemas/APIValidationError"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/purchases": {
      "get": {
        "tags": [
          "Purchases Transaction"
        ],
        "operationId": "getPurchases",
        "summary": "Get Recently Recorded Purchase Transaction",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APISuccessResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "allOf": [
                              {
                                "type": "object",
                                "properties": {
                                  "id": {
                                    "type": "string"
                                  },
                                  "supplierName": {
                                    "type": "string"
                                  }
                                }
                              },
                              {
                                "$ref": "#/components/schemas/TransactionListResponse"
                              }
                            ]
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "message": "Sales Fetched Successfully",
                  "data": [
                    {
                      "id": "92cb1d94-85ee-4704-a4bf-43340807d717",
                      "supplierName": "CV. TBS",
                      "productName": "TBS Plasma",
                      "transactionDate": "2023-07-24 15:00:25.120",
                      "totalWeight": 1500,
                      "receivedWeight": 750,
                      "total": 260000,
                      "paymentMethod": "Cash",
                      "paymentStatus": "Paid",
                      "deliveryStatus": "Partial Deliveed",
                      "isPaid": true,
                      "isDelivered": false
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/purchase/{transactionId}": {
      "get": {
        "tags": [
          "Purchases Transaction"
        ],
        "operationId": "getPurchasesTransactionById",
        "summary": "Get Sales Transaction By Id",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "transactionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APISuccessResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "object",
                          "allOf": [
                            {
                              "type": "object",
                              "properties": {
                                "id": {
                                  "type": "string"
                                },
                                "supplierId": {
                                  "type": "string"
                                }
                              }
                            },
                            {
                              "$ref": "#/components/schemas/TransactionDetailResponse"
                            }
                          ]
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "message": "Sales Detail Fetched Successfully",
                  "data": {
                    "id": "92cb1d94-85ee-4704-a4bf-43340807d717",
                    "supplierId": "0ccb1d94-85ee-4704-a4bf-43340807d717",
                    "productId": "92cb1d94-85ee-4704-a4bf-43340807d717",
                    "transactionDate": "2023-07-24 15:00:25.120",
                    "grossWeight": 2500,
                    "tareWeight": 1000,
                    "nettoWeight": 1500,
                    "dedicationPersentage": 4,
                    "totalWeight": 1440,
                    "receivedWeight": 750,
                    "price": 50000,
                    "total": 72000000,
                    "vehicleRegistrationNumber": "BK 123 ABC",
                    "paymentMethod": "Cash",
                    "paymentStatus": "Paid",
                    "deliveryStatus": "Partial Deliveed",
                    "sourceOfPurcahse": "-",
                    "additionalNotes": null,
                    "proofImages": [
                      "https://link.id/a",
                      "https://link.id/b",
                      "https://link.id/c"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/purchase/store": {
      "post": {
        "tags": [
          "Purchases Transaction"
        ],
        "operationId": "storePurchases",
        "summary": "Store Sales Transaction",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionStoreBody"
              },
              "example": {
                "supplierId": "0ccb1d94-85ee-4704-a4bf-43340807d717",
                "productId": "92cb1d94-85ee-4704-a4bf-43340807d717",
                "grossWeight": 2500,
                "tareWeight": 1000,
                "dedicationPersentage": 4,
                "receivedWeight": 750,
                "price": 50000,
                "total": 72000000,
                "vehicleRegistrationNumber": "BK 123 ABC",
                "paymentMethod": "Cash",
                "paymentStatus": "Paid",
                "deliveryStatus": "Partial Deliveed",
                "sourceOfPurcahse": "-",
                "additionalNotes": null,
                "proofImages": [
                  "blob string"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APISuccessResponse"
                },
                "example": {
                  "success": true,
                  "message": "Purchases Data Stored Successfully"
                }
              }
            }
          },
          "400": {
            "description": "Sales Store Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APIErrorResponse"
                    },
                    {
                      "$ref": "#/components/schemas/APIValidationError"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/purchase/request": {
      "put": {
        "tags": [
          "Purchases Transaction"
        ],
        "operationId": "updatePurchases",
        "summary": "Send Update Request to Admin",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "supplierId": {
                        "type": "string"
                      }
                    }
                  },
                  {
                    "$ref": "#/components/schemas/TransactionStoreBody"
                  }
                ]
              },
              "example": {
                "transactionId": "92cb1d94-85ee-4704-a4bf-43340807d717",
                "requestChanges": {
                  "grossWeight": 2500,
                  "tareWeight": 1000
                },
                "reason": "dummy"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APISuccessResponse"
                },
                "example": {
                  "success": true,
                  "message": "Sent Request Successfully"
                }
              }
            }
          },
          "400": {
            "description": "Sales Store Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APIErrorResponse"
                    },
                    {
                      "$ref": "#/components/schemas/APIValidationError"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "APISuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "APIErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "errorCode": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "APIValidationError": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "field": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "TransactionListResponse": {
        "type": "object",
        "properties": {
          "productName": {
            "type": "string"
          },
          "transactionDate": {
            "type": "string"
          },
          "totalWeight": {
            "type": "number"
          },
          "receivedWeight": {
            "type": "number"
          },
          "total": {
            "type": "number"
          },
          "paymentMethod": {
            "type": "string"
          },
          "paymentStatus": {
            "type": "string"
          },
          "deliveryStatus": {
            "type": "string"
          },
          "isPaid": {
            "type": "boolean"
          },
          "isDelivered": {
            "type": "boolean"
          }
        }
      },
      "TransactionDetailResponse": {
        "type": "object",
        "properties": {
          "productId": {
            "type": "string"
          },
          "transactionDate": {
            "type": "string"
          },
          "grossWeight": {
            "type": "number"
          },
          "tareWeight": {
            "type": "number"
          },
          "nettoWeight": {
            "type": "number"
          },
          "dedicationPersentage": {
            "type": "number"
          },
          "totalWeight": {
            "type": "number"
          },
          "receivedWeight": {
            "type": "number"
          },
          "price": {
            "type": "number"
          },
          "total": {
            "type": "number"
          },
          "vehicleRegistrationNumber": {
            "type": "string"
          },
          "paymentMethod": {
            "type": "string"
          },
          "paymentStatus": {
            "type": "string"
          },
          "deliveryStatus": {
            "type": "string"
          },
          "sourceOfPurcahse": {
            "type": "string"
          },
          "additionalNotes": {
            "type": "string"
          },
          "proofImages": {
            "$ref": "#/components/schemas/productImages"
          }
        }
      },
      "TransactionStoreBody": {
        "type": "object",
        "properties": {
          "productId": {
            "type": "string"
          },
          "grossWeight": {
            "type": "number"
          },
          "tareWeight": {
            "type": "number"
          },
          "dedicationPersentage": {
            "type": "number"
          },
          "receivedWeight": {
            "type": "number"
          },
          "price": {
            "type": "number"
          },
          "total": {
            "type": "number"
          },
          "vehicleRegistrationNumber": {
            "type": "string"
          },
          "paymentMethod": {
            "type": "string"
          },
          "paymentStatus": {
            "type": "string"
          },
          "deliveryStatus": {
            "type": "string"
          },
          "sourceOfPurcahse": {
            "type": "string"
          },
          "additionalNotes": {
            "type": "string"
          },
          "proofImages": {
            "$ref": "#/components/schemas/productImages"
          }
        }
      },
      "productImages": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}