{
  "openapi": "3.0.0",
  "info": {
    "title": "Buku Sawit Authentication Service API",
    "description": "API ini dipakai untuk melakukan authentikasi dan manajemen akun untuk sistem buku sawit, baik untuk Front office maupun Back office.\n\n# Keterangan Penggunaan API\nSilahkan atur alamat API sesuai dengan ketentuan dan mode berikut ini.\n## Development Mode\n` http://localhost:8000`\n## Production Mode (Planning)\n` http://192.168.10.2`",
    "contact": {
      "email": "it@ninosoftwarehouse.id"
    },
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "http://localhost:8000"
    }
  ],
  "paths": {
    "/api/v1/register": {
      "post": {
        "tags": [
          "Customer Registration"
        ],
        "summary": "Register a new account",
        "operationId": "registerAccount",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterAccountRequest"
              },
              "example": {
                "firstName": "Supardi",
                "lasName": "Minamoto",
                "companyName": "PT. Saya Mau",
                "companyAddress": "Jl. Serdang No. 1",
                "email": "supardi@sayamau.id",
                "phoneNumber": "62811600654",
                "password": "test12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Account registration successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APISuccessResponse"
                },
                "example": {
                  "success": true,
                  "mesage": "Account Registered Successfully"
                }
              }
            }
          },
          "400": {
            "description": "Registration Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400"
                },
                "examples": {
                  "Invalid Input": {
                    "value": {
                      "success": false,
                      "errorCode": "INPUT_VALIDATION_ERROR",
                      "message": "Input Validation Error",
                      "errors": [
                        {
                          "field": "email",
                          "message": "Format email tidak valid!"
                        },
                        {
                          "field": "password",
                          "message": "Password harus memiliki panjang minimal 8 karakter!"
                        }
                      ]
                    }
                  },
                  "User Exists": {
                    "value": {
                      "success": false,
                      "errorCode": "REGISTER_USER_EXISTS",
                      "message": "User was exists"
                    }
                  }
                }
              }
            }
          }
        },
        "x-swagger-router-controller": "CustomerRegistration"
      }
    },
    "/api/v1/activation/{activationCode}": {
      "get": {
        "tags": [
          "Customer Registration"
        ],
        "summary": "Activate a registered account",
        "operationId": "activateAccount",
        "parameters": [
          {
            "name": "activationCode",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Account activation successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccountActivationSuccessResponse"
                }
              }
            }
          },
          "400": {
            "description": "Activation code not found or expired",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccountActivationExpiredResponse"
                },
                "example": {
                  "success": false,
                  "errorCode": "ACTIVATION_LINK_INVALID",
                  "message": "Activation Link Was Invalid or Expired"
                }
              }
            }
          }
        },
        "x-swagger-router-controller": "CustomerRegistration"
      }
    },
    "/api/v1/login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "User login",
        "operationId": "login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              },
              "examples": {
                "Primary User (Backoffice)": {
                  "value": {
                    "email": "airani@example.com",
                    "password": "SayaLupa123"
                  }
                },
                "Employee User (Frontoffice or Backoffice)": {
                  "value": {
                    "username": "airani",
                    "password": "SayaLupa123"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Login successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginSuccessResponse"
                },
                "example": {
                  "success": true,
                  "message": "Login Success",
                  "data": {
                    "accessToken": "accessToken"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Login Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400"
                },
                "example": {
                  "success": false,
                  "errorCode": "INPUT_VALIDATION_ERROR",
                  "message": "Input Validation Error",
                  "errors": [
                    {
                      "field": "email",
                      "message": "Format email tidak valid!"
                    },
                    {
                      "field": "password",
                      "message": "Password harus memiliki panjang minimal 8 karakter!"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Invalid Login Credentials",
            "content": {
              "aplication/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginInvalidResponse"
                },
                "examples": {
                  "emailNotFound": {
                    "value": {
                      "success": false,
                      "errorCode": "CREDENTIAL_EMAIL_NOT_REGISTERED",
                      "message": "E-Mail Not Registered"
                    }
                  },
                  "usernameNotFound": {
                    "value": {
                      "success": false,
                      "errorCode": "CREDENTIAL_USERNAME_NOT_REGISTERED",
                      "message": "E-Mail Not Registered"
                    }
                  },
                  "passwordMismatch": {
                    "value": {
                      "success": false,
                      "errorCode": "CREDENTIAL_PASSWORD_MISMATCH",
                      "message": "Password Mismatch"
                    }
                  }
                }
              }
            }
          }
        },
        "x-swagger-router-controller": "Authentication"
      }
    },
    "/api/v1/logout": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "User Logout",
        "operationId": "logout",
        "responses": {
          "200": {
            "description": "Logout Successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APISuccessResponse"
                },
                "example": {
                  "success": true,
                  "message": "User Logged out Successfully"
                }
              }
            }
          },
          "500": {
            "description": "General Error From Server",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                },
                "example": {
                  "success": false,
                  "errorCode": "INTERNAL_SERVER_ERROR",
                  "message": "Internal Server Error"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/profile": {
      "get": {
        "tags": [
          "Profile Account"
        ],
        "operationId": "getAccountDetails",
        "summary": "Get account details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProfileAccountResponse"
                },
                "example": {
                  "success": true,
                  "message": "Account Information Fetched Successfully",
                  "data": {
                    "firstName": "Tsukiko",
                    "lastName": "Sorano",
                    "companyName": "PT. Kira Kira Sukses",
                    "companyAddress": "Jl. Pasar Senen No. 10, Jakarta Pusat, DKI Jakarta",
                    "email": "airani@example.com",
                    "phoneNumber": "6281375157218"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Profile Account"
        ],
        "operationId": "updateAccountDetails",
        "summary": "Update account details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProfileUpdateRequest"
              },
              "example": {
                "firstName": "Tsukiko",
                "companyName": "PT. Dummy",
                "companyAddress": "Jl. Dummy",
                "email": "airaniii@example.com",
                "phoneNumber": "62811600654"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Account details updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APISuccessResponse"
                },
                "example": {
                  "success": true,
                  "message": "Account details updated successfully"
                }
              }
            }
          },
          "400": {
            "description": "Invalid request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APIErrorResponse"
                    },
                    {
                      "$ref": "#/components/schemas/APIValidationError"
                    }
                  ]
                },
                "example": {
                  "success": false,
                  "errorCode": "INPUT_VALIDATION_ERROR",
                  "message": "Input Validation Error",
                  "errors": [
                    {
                      "field": "email",
                      "message": "Format email tidak valid."
                    },
                    {
                      "field": "phoneNumber",
                      "message": "Format nomor handphone tidak valid"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/profile/password": {
      "put": {
        "tags": [
          "Profile Account"
        ],
        "operationId": "changePassword",
        "summary": "Change Password for Customer",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "currentPassword": {
                    "type": "string"
                  },
                  "newPassword": {
                    "type": "string"
                  },
                  "confirmPassword": {
                    "type": "string"
                  }
                },
                "required": [
                  "currentPassword",
                  "newPassword",
                  "confirmPassword"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APISuccessResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid Input or Missmatch",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "oneOf": [
                    {
                      "type": "object",
                      "allOf": [
                        {
                          "$ref": "#/components/schemas/APIErrorResponse"
                        },
                        {
                          "$ref": "#/components/schemas/APIValidationError"
                        }
                      ]
                    },
                    {
                      "$ref": "#/components/schemas/APIErrorResponse"
                    }
                  ]
                },
                "examples": {
                  "ValidationError": {
                    "value": {
                      "success": false,
                      "errorCode": "INPUT_VALIDATION_ERROR",
                      "message": "Input Validation Error",
                      "errors": [
                        {
                          "field": "confirmPassword",
                          "message": "Passwords do not match"
                        }
                      ]
                    }
                  },
                  "OldPasswordMissmatch": {
                    "value": {
                      "success": false,
                      "errorCode": "CREDENTIAL_PASSWORD_MISMATCH",
                      "message": "Credential Password Mismatch"
                    }
                  },
                  "InvalidCustomerOrAccountId": {
                    "value": {
                      "success": false,
                      "errorCode": "CREDENTIAL_ACCOUNT_NOT_FOUND",
                      "message": "Invalid Account ID"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "APISuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "APIErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "errorCode": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "APIValidationError": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/APIValidationError_errors"
            }
          }
        }
      },
      "RegisterAccountRequest": {
        "required": [
          "companyAddress",
          "companyName",
          "email",
          "firstName",
          "password",
          "phoneNumber"
        ],
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "companyName": {
            "type": "string"
          },
          "companyAddress": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "phoneNumber": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "AccountActivationSuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "success": true,
          "message": "Account Activated Successfully"
        }
      },
      "AccountActivationExpiredResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "errorCode": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "LoginRequest": {
        "required": [
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "LoginSuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/LoginSuccessResponse_data"
          }
        }
      },
      "LoginInvalidResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "errorCode": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "inline_response_400": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/APIErrorResponse"
          },
          {
            "$ref": "#/components/schemas/APIValidationError"
          }
        ]
      },
      "APIValidationError_errors": {
        "type": "object",
        "properties": {
          "field": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "LoginSuccessResponse_data": {
        "type": "object",
        "properties": {
          "accessToken": {
            "type": "string"
          }
        }
      },
      "ProfileAccountResponse": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/APISuccessResponse"
          },
          {
            "type": "object",
            "properties": {
              "data": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "companyName": {
                    "type": "string"
                  },
                  "companyAddress": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "phoneNumber": {
                    "type": "string"
                  }
                }
              }
            }
          }
        ]
      },
      "ProfileUpdateRequest": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "companyName": {
            "type": "string"
          },
          "companyAddress": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "phoneNumber": {
            "type": "string"
          }
        },
        "required": [
          "firstName",
          "companyName",
          "companyAddress",
          "email",
          "phoneNumber"
        ]
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}